Electric-Coin-Company/zcash-light-client-ffi

CONTRIBUTING.md
This is a copy of the version present on ZcashLightClientKit
Closes #10
=> [#10] Update "Commit Messages" section of CONTRIBUTING.md

.gitignore, CHANGELOG.md, libzcashlc.podspec, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
UnifiedViewingKey had a bug that made it incompatible with ZIP 316.
Depends on https://github.com/zcash/librustzcash/pull/570.
Closes #15.
Closes #16.
=> Replace UnifiedViewingKey with UnifiedFullViewingKey

rust/src/lib.rs
Swift lacks fixed-size arrays, so this change makes for a cleaner API on the Swift side, at the expense of slightly less type safety in the C api.
=> Change memo parameters back to *const u8

rust/src/lib.rs
For the moment, these are inefficient, requiring separate database queries rather than a join at the database level. This is a temporary fix, as we're not certain how we will best represent transparent balances given potential address linkability issues presented when rolling unified addresses.
=> Add methods to obtain total transparent account balances.

rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
Reverts zcash-hackworks/zcash-light-client-ffi#54
=> Revert "Shield all available funds for the account in `zcashlc_shield_funds`"

rust/Cargo.lock, rust/Cargo.toml
file the get_total_transparent_balance_for_account issue
=> update to latest librustzcash rev

CHANGELOG.md, libzcashlc.podspec, releases/XCFramework/libzcashlc.xcframework/ios-arm64/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/ios-arm64_x86_64-simulator/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/macos-arm64_x86_64/libzcashlc.framework/Headers/zcashlc.h, rust/Cargo.lock, rust/Cargo.toml
Closes #58
Adds the version to the changelog, podspec and Cargo.toml
=> [#58] release 0.1.0

CHANGELOG.md
This build creates the binaries and updates the CHANGELOG.md Closes #75
=> [#75] Release 0.1.1

Package.swift
=> [#34] Additional change to fix SwiftPackageManager deprecation Warning

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
=> Outbound transactions shows the wrong amount on `v_transactions`

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
=> [#91] release 0.3.1

CHANGELOG.md, releases/XCFramework/libzcashlc.xcframework/ios-arm64/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/ios-arm64_x86_64-simulator/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/macos-arm64_x86_64/libzcashlc.framework/Headers/zcashlc.h, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/os_log/layer.rs
=> Migrate to Rust crate versions with fast spendability support

rust/Cargo.lock, rust/Cargo.toml
=> Fix checkpoint depth bug

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
* Update `rust/Cargo.toml` and `CHANGELOG.md`.
* `cd rust; cargo update libzcashlc`
=> Release 0.4.1

rust/src/lib.rs
Closes Electric-Coin-Company/zcash-light-client-ffi#101.
=> Replace Sapling balance and scan progress FFIs with wallet summary FFI

rust/src/lib.rs
=> [#114] Create a transaction proposal from ZIP-321 payment URI

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
This fixes an error in version 0.7.0 that could cause problems for wallets sending notes to their own external addresses.
=> zcash_light_client_ffi release version 0.7.1

CHANGELOG.md, rust/src/lib.rs
=> Remove `zcashlc_get_memo_as_utf8`

rust/src/lib.rs, rust/src/tor.rs
This was intended to be in Electric-Coin-Company/zcash-light-client-ffi#193 but I forgot to push it to the PR before merging the latter.
=> Expose mined height from `zcashlc_tor_lwd_conn_fetch_transaction`

rust/src/lib.rs
Replaces #206 (branch name has changed so that an automatic preview build can be created.)
=> Allow shielding from multiple transparent addresses.

CONTRIBUTING.md
New PR because #234 was merged a bit too eagerly.
=> Document the general development and release process
