CHANGELOG.md, rust/src/lib.rs
Allow the caller to supply explicitly the number of confirmations required for TXOs when querying balances or sending funds.
Fixes #8
Fixes #9
=> Add min_confirmations argument to balance & spend methods.

rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
Remove Spending key from `shield_funds` and use Sapling extended full viewing key instead.
This is moving work forward to ultimately use UnifiedFullViewingKey from the db and only requiring account priv key as a parameter
=> Remove Spending key from `shield_funds`

CHANGELOG.md, rust/src/lib.rs
Closes #26
This implements changes to FFI functions `zcashlc_shield_funds`
and `zcashlc_create_to_address` to accept Memos as slices of
bytes instead of a null-terminated UTF-8 char array.
The receiving functions will attempt to parse the receiving
bytes as ZIP-302 compliant and will fail if the rust side
fails to parse create `MemoBytes` from the respective `[u8]`.
Add support for type safe memos by retrieving them as bytes with
`zcashlc_get_received_memo`
`zcashlc_get_sent_memo`
`zcashlc_byte_array_free`
these functions will have to be adopted by the RustWelding layer on
ZcashLightClientKit
=> [#26] make FFI accept byte slices for memos

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
This also updates `zcashlc_create_to_address` to take a unified spending key for spending authority instead of a Sapling extended spending key.
=> Use unified spending keys instead of Sapling extended spending keys.

rust/src/lib.rs
This enables `deny(unsafe_op_in_unsafe_fn)` globally and adds `unsafe` annotations as necessary. fixes #65
=> `unsafe` annotations

rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
First time I failed to include the ZIP 317 changes in the feature branch.
closes #65
=> Update to librustzcash version 0.7, take 2

rust/Cargo.lock, rust/Cargo.toml
This eliminates duplicate dependencies on fixedbitset and petgraph.
=> Update to the latest version of schemer

CHANGELOG.md, libzcashlc.podspec, rust/Cargo.lock, rust/Cargo.toml
Updating:
````
- zcash_client_backend v0.6.0 -> v0.6.1
- zcash_client_sqlite v0.4.0 -> v0.4.2
````
This fixes the following issue
- [#72] fixes get_transparent_balance() fails when no UTXOs
Closes #72
=> [#72] fixes get_transparent_balance() fails when no UTXOs

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
This is the initial implementation of the rust FFI code for using FsBlockDb from Swift. 
It's based on https://github.com/zcash/zcash-android-wallet-sdk/pull/804
It points to a branch because I need to code a fmt::Display trait compliance for the FsBlockError enum which I could implement from the FFI module itself. 
Closes #81 
Closes #73
=> Implement FsBlockDb

CHANGELOG.md, Package.swift, README.md
Closes #34 
This fixes a deprecation warning around the name of the package. 
needs a subsequent PR on ZcashLightClientKit #754
=> [#34] Fix SwiftPackageManager deprecation Warning

releases/XCFramework/libzcashlc.xcframework/ios-arm64/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/ios-arm64_x86_64-simulator/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/macos-arm64_x86_64/libzcashlc.framework/Headers/zcashlc.h, rust/src/lib.rs
Closes #83
This allow the SDK to use the seed phrase signature for identifiers that are coupled to it such as synchronizer aliases without revealing anything about the seed itself
=> [#83] Get Fingerprint for Seed bytes

rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
Closes #88
uses `truncate_to_height` and `get_min_unspent_height`
make xcframework
=> [#88] unmined transaction shows note value spent instead of tx value

rust/src/lib.rs, rust/wrapper.c, rust/wrapper.h
This enables development on non-Apple machines, and potentially in future usage of the Swift SDK with non-Apple targets.
=> Conditionally compile Apple-specific APIs

rust/src/lib.rs
This also modifies shielding behavior so that shielded funds are sent to the Orchard pool instead of to Sapling.
=> Send change to Orchard by default

support/Info.plist
For whatever reason, this works around a bug in XCode 15.3.
Part of Electric-Coin-Company/zashi-ios#1166.
=> Set `MinimumOSVersion` to a wildly-high value

Makefile, support/platform-Info.plist
A bug in the XCode 15.3 build system causes a dummy framework folder to be included in the app bundle when it depends on a statically linked framework (like this one). This causes app validation to fail both in the simulator and when pushing an app build to the App Store Connect.
We work around the bug by adding a dummy `Info.plist` to the platform frameworks, with a `MinimumOSVersion` that is wildly high to ensure it can't actually be used.
Part of Electric-Coin-Company/zashi-ios#1166.
=> Add dummy `Info.plist` to platform frameworks

rust/src/lib.rs
This removes an `expect` call that risked crashing the app in the case of database corruption, potentially hiding other bugs.
=> Return an error instead of a panic in the case of data corruption.

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/tor.rs
We fetch exchange rates on the Rust side of the FFI instead of exposing a direct URL GET method, in order to enable fetching from multiple sources simultaneously to make better use of Arti's async nature.
=> Add FFI methods for fetching exchange rates over Tor

CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
This corrects an error in the `zcash_client_sqlite` database migration system that could lead to problems in wallet initialization for some wallets.
=> release zcash-light-client-ffi version 0.9.1

.github/workflows/build-binary-preview.yml
- After changing from `-` to `/` logical separation, the `-preview` suffix was mis-interpretable as part of the version.
- Using a `preview` suffix would potentially cause the workflow to recursively loop, because the workflow branch filter would match both the release / hotfix branches, and every preview branch. We now use a `preview` prefix to domain-separate the preview branches.
=> CI: Change naming pattern for binary preview branches to avoid bugs

.github/workflows/build-binary-preview.yml
This is necessary to get the stefanzweifel/git-auto-commit-action@v5 action to set the upstream branch.
=> CI: Specify branch to commit and push binary previews to

.github/workflows/build-binary-preview.yml, README.md
This is necessary to discover any existing binary previews for the current branch, so we can merge to it instead of overwriting it.
=> Fix binary preview

CHANGELOG.md, releases/XCFramework/libzcashlc.xcframework/ios-arm64/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/ios-arm64_x86_64-simulator/libzcashlc.framework/Headers/zcashlc.h, releases/XCFramework/libzcashlc.xcframework/macos-arm64_x86_64/libzcashlc.framework/Headers/zcashlc.h, rust/Cargo.lock, rust/Cargo.toml, rust/src/ffi.rs, rust/src/lib.rs
This PR stacks on #236 and changes the FFI API to include `ConfirmationsPolicy`.
=> feature: librustzcash update confirmations policy part 2

rust/Cargo.lock, rust/Cargo.toml
This will be merged via direct push with build artifacts to the hotfix/0.18.2 branch.
=> Update to `zcash_client_sqlite 0.18.3`
